### ISSUE TITLE
Add support for writing to a new dcm file?

### ISSUE THREAD

**Issue by Illviljan** [dkuschmierz/dcmReader#2]
When I've gotten to the point of wanting to open a dcm-file with python I usually want to change some parameter in it in a more advanced way. 
Once that's done I want to save it as a dcm-file again.

Basically:
```python
dcm = DcmReader()
dcm.read("tests/Sample.dcm")

# Do something advanced:
dcm.getcharacteristicMap[0] = dcm.getcharacteristicMap[1]

# Save to new file:
dcm.save("tests/Sample_new.dcm")
```

Could dcmReader support this?

**Comment by dkuschmierz** [comment]
Also thought of this option, as this would it make it very easy to order a DCM file alphabetically. I think this is also very easy because I only have to modify the __str__ functions. I will have a look in the next few weeks...

**Comment by dkuschmierz** [comment]
Added write support in the latest function. This also can be used to easily sort a DCM file...
